
  // Please do not edit. This file is auto generated by scripts/parseElement.js
  export type Element = {
    name: string;
    version: string;
    url: string;
  };
  export const elements: Element[] = [
    {
      name: '@exm/exm-breadcrumbs',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-breadcrumbs',
    },{
      name: '@exm/exm-button',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-button',
    },{
      name: '@exm/exm-chip-input',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-chip-input',
    },{
      name: '@exm/exm-collapsed',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-collapsed',
    },{
      name: '@exm/exm-copy-to-clipboard',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-copy-to-clipboard',
    },{
      name: '@exm/exm-dialogs',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-dialogs',
    },{
      name: '@exm/exm-form',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-form',
    },{
      name: '@exm/exm-form-drawer',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-form-drawer',
    },{
      name: '@exm/exm-grid',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-grid',
    },{
      name: '@exm/exm-markdown-editor',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-markdown-editor',
    },{
      name: '@exm/exm-navigation',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-navigation',
    },{
      name: '@exm/exm-radio',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-radio',
    },{
      name: '@exm/exm-search',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-search',
    },{
      name: '@exm/exm-snackbar',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-snackbar',
    },{
      name: '@exm/exm-sortable',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-sortable',
    },{
      name: '@exm/exm-theme',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-theme',
    },{
      name: '@exm/exm-tooltip',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-tooltip',
    },{
      name: '@exm/exm-upload',
      version: '1.0.0',
      url: 'https://www.npmjs.com/package/@exm/exm-upload',
    },
  ];
